language: python
dist: xenial
python:
  - "3.7"
before_install:
  - pip install pylint
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=C,W,R es_responder.py
