language: python
python:
  - "3.6"
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - python test_base.py TestErrors TestDiagnostics
  - pylint --disable=C,W,R es_responder.py
